/*******************************************************************************
 * Copyright (C) 2018 Davide Daffonchio
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ssa;


import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JEditorPane;

import common.LotusVBE;
import net.miginfocom.swing.MigLayout;


/**
 *
 * @author Davide
 */
public class StatusSheet extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	int index;

	/**
	 * Creates new form StatusSheet
	 */
	public StatusSheet(int index) { //index from 0 to 12 are reserved to players, >13 are for team data
		this.setIconImage(LotusVBE.img.lotusLogo);
		this.addWindowListener(new WindowAdapter(){
			@Override
			public void windowClosing(WindowEvent e){
				if(index<13)
					MainController.playerButtons[index].setEnabled(true);
			}
		});
		this.setIconImage(LotusVBE.img.lotusLogo);
		if(index<13){
			MainController.playerButtons[index].setEnabled(false);
		}
		this.index = index;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		statusArea = new JEditorPane();
		statusArea.setContentType("text/html");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Status");

		statusArea.setEditable(false);
		//statusArea.setColumns(20);
		statusArea.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
		//statusArea.setRows(5);
		statusArea.setMargin(new java.awt.Insets(2, 3, 2, 2));
		statusArea.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				statusAreaKeyPressed(evt);
			}
		});
		getContentPane().setLayout(new MigLayout("", "[761px,grow]", "[686px,grow,fill]"));
		jScrollPane1.setViewportView(statusArea);
		getContentPane().add(jScrollPane1, "cell 0 0,grow");

		pack();
		setLocationRelativeTo(null); //window to center
	}// </editor-fold>//GEN-END:initComponents

	private void statusAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusAreaKeyPressed
		//html debugger
		/*PrintWriter writer=null;
		try {
			writer = new PrintWriter("test.html", "UTF-8");
		} catch (FileNotFoundException | UnsupportedEncodingException e) {
			e.printStackTrace();
		}
    	writer.println(statusArea.getText());
    	writer.close();*/
		//esci con qualunque tasto
		if(index<13)
			MainController.playerButtons[index].setEnabled(true);
		this.dispose();
	}//GEN-LAST:event_statusAreaKeyPressed

	public void setText(String s){
		statusArea.setText("<html>"+LotusVBE.tableHead()+"<body>"+s+"<br>"+"<font size=\"6\" face=\"verdana\">"+SSALotus.lang.getString("pressKeyToQuit")+"</font>"+"</body>"+"</html>");
	}

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	JEditorPane statusArea;
	// End of variables declaration//GEN-END:variables
}
